item {
    id: 1
    name: 'baliser_ok'
}
item {
    id: 2
    name: 'baliser_aok'
}
item {
    id: 3
    name: 'baliser_nok'
}
item {
    id: 4
    name: 'insulator_ok'
}
item {
    id: 5
    name: 'insulator_nok'
}
item {
    id: 6
    name: 'bird_nest'
}
item {
    id: 7
    name: 'stockbridge_ok'
}
item {
    id: 8
    name: 'stockbridge_nok'
}
item {
    id: 9
    name: 'spacer_ok'
}
item {
    id: 10
    name: 'spacer_nok'
}
item {
    id: 11
    name: 'insulator_unk'
}